# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

newAgent <- function(state, death_time = NA_real_) {
    .Call(`_ABM_newAgent`, state, death_time)
}

getID <- function(agent) {
    .Call(`_ABM_getID`, agent)
}

getState <- function(agent) {
    .Call(`_ABM_getState`, agent)
}

schedule <- function(agent, event) {
    invisible(.Call(`_ABM_schedule`, agent, event))
}

unschedule <- function(agent, event) {
    invisible(.Call(`_ABM_unschedule`, agent, event))
}

clearEvents <- function(agent) {
    invisible(.Call(`_ABM_clearEvents`, agent))
}

setState <- function(agent, value) {
    invisible(.Call(`_ABM_setState`, agent, value))
}

leave <- function(agent) {
    .Call(`_ABM_leave`, agent)
}

setDeathTime <- function(agent, time) {
    invisible(.Call(`_ABM_setDeathTime`, agent, time))
}

newRandomMixing <- function() {
    .Call(`_ABM_newRandomMixing`)
}

newContact <- function(r6) {
    .Call(`_ABM_newContact`, r6)
}

newCounter <- function(name, from, to = NULL, initial = 0L) {
    .Call(`_ABM_newCounter`, name, from, to, initial)
}

newStateLogger <- function(name, agent, state) {
    .Call(`_ABM_newStateLogger`, name, agent, state)
}

newEvent <- function(time, handler) {
    .Call(`_ABM_newEvent`, time, handler)
}

getTime <- function(event) {
    .Call(`_ABM_getTime`, event)
}

newConfigurationModel <- function(rng) {
    .Call(`_ABM_newConfigurationModel`, rng)
}

newPopulation <- function(n, initializer = NULL) {
    .Call(`_ABM_newPopulation`, n, initializer)
}

addAgent <- function(population, agent) {
    invisible(.Call(`_ABM_addAgent`, population, agent))
}

getSize <- function(population) {
    .Call(`_ABM_getSize`, population)
}

getAgent <- function(population, i) {
    .Call(`_ABM_getAgent`, population, i)
}

addContact <- function(population, contact) {
    invisible(.Call(`_ABM_addContact`, population, contact))
}

setStates <- function(population, states) {
    invisible(.Call(`_ABM_setStates`, population, states))
}

newSimulation <- function(n, initializer = NULL) {
    .Call(`_ABM_newSimulation`, n, initializer)
}

runSimulation <- function(sim, time) {
    .Call(`_ABM_runSimulation`, sim, time)
}

resumeSimulation <- function(sim, time) {
    .Call(`_ABM_resumeSimulation`, sim, time)
}

addLogger <- function(sim, logger) {
    invisible(.Call(`_ABM_addLogger`, sim, logger))
}

addTransition <- function(sim, from, contact_from, to, contact_to, contact, waiting_time, to_change_callback = NULL, changed_callback = NULL) {
    invisible(.Call(`_ABM_addTransition`, sim, from, contact_from, to, contact_to, contact, waiting_time, to_change_callback, changed_callback))
}

stateMatch <- function(state, rule) {
    .Call(`_ABM_stateMatch`, state, rule)
}

newExpWaitingTime <- function(rate) {
    .Call(`_ABM_newExpWaitingTime`, rate)
}

newGammaWaitingTime <- function(shape, scale) {
    .Call(`_ABM_newGammaWaitingTime`, shape, scale)
}

newRWaitingTime <- function(rng) {
    .Call(`_ABM_newRWaitingTime`, rng)
}

getWaitingTime <- function(generator, time) {
    .Call(`_ABM_getWaitingTime`, generator, time)
}

